[package]
name = "wasi-spi"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
wasmtime = { version = "39.0.0", features = ["component-model"] }
wasmtime-wasi = "39.0.0"
embedded-hal = "1.0"
